Address Digital-1183
utkdigitalinitiatives/canopy pull request #9
Opened 2021-08-17 22:59 UTC by markpbaggett

[DIGITAL-1183](https://jirautk.atlassian.net/browse/DIGITAL-1183)

# What Does This Do

Adds a Description component to details with minimal styling.

# How Does It Work

2021-08-18 20:11 UTC, mathewjordan requested changes
I've made a comment regarding the Sass. Let's talk about it but I think if we want to go with a columned layout like your original committed, we may just want to add additional elements wrapping our rows. This will give us much greater control over that type of styling. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_htmlelementdiv_elements

2021-08-18 20:11 UTC, mathewjordan commented on src/sass/components/_description.scss
> +}
I've thought about this a bit since you mentioned it. Doing it your way, each `<dt>` is on the same row as its first respective `<dd>` . If either of these happens to wrap to the next line, a gap will form and be visible to the user. To overcome issues with responsiveness, and avoid cluttering the `<dl>` structure with elements other than `<dt>` and `<dd>`, it may be best to just do a non-flex layout.

_Example of a gap forming in first `<dt>` row on mobile viewport._
![image](https://user-images.githubusercontent.com/7376450/129964634-eb0d6413-2dea-406c-abad-eb6d357f71a6.png)


My suggestion below will output this like:
![image](https://user-images.githubusercontent.com/7376450/129964297-32d93441-5044-4b51-a864-1a6d431ca267.png)

```suggestion
dl.canopy-metadata {
  dt {
    font-weight: 700;
    margin-top: 1em;

    &:first-child {
      margin-top: 0;
    }
  }

  dd {
    margin: 0;
  }
}
```

2021-08-19 00:44 UTC, markpbaggett commented
@mathewjordan this is ready to be reviewed again.

2021-08-19 01:02 UTC, mathewjordan approved these changes
:shipit:

2021-08-19 01:03 UTC, merged